### ISSUE TITLE
Conflict with guard-minitest or notiffany?

### ISSUE THREAD

**Issue by thbar** [tmate-io/tmate#78]
On a ruby project, I get this error when launching minitest, only under tmate:

```
/Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/tmux.rb:35:in `version': undefined method `[]' for nil:NilClass (NoMethodError)
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/tmux.rb:194:in `_check_available'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/base.rb:59:in `initialize'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/detected.rb:92:in `new'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/detected.rb:92:in `add'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/detected.rb:64:in `block (2 levels) in detect'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/detected.rb:62:in `each'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/detected.rb:62:in `detect'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/detected.rb:62:in `block in detect'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/detected.rb:61:in `each'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier/detected.rb:61:in `detect'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier.rb:105:in `initialize'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier.rb:42:in `new'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/notiffany-0.0.8/lib/notiffany/notifier.rb:42:in `connect'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/guard-2.13.0/lib/guard/notifier.rb:11:in `connect'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/guard-2.13.0/lib/guard/notifier.rb:31:in `notify'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/guard-compat-1.2.1/lib/guard/compat/plugin.rb:113:in `notify'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/guard-minitest-2.4.4/lib/guard/minitest/notifier.rb:31:in `notify'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/guard-minitest-2.4.4/lib/guard/minitest/reporter.rb:10:in `report'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/minitest-5.8.4/lib/minitest.rb:637:in `each'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/minitest-5.8.4/lib/minitest.rb:637:in `report'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/minitest-5.8.4/lib/minitest.rb:134:in `run'
  from /Users/thbar/.rvm/gems/ruby-2.3.0@project/gems/minitest-5.8.4/lib/minitest.rb:56:in `block in autorun'
```

To reproduce, create a `Gemfile` with:

``` ruby
group :development do
  gem 'awesome_print'
  gem 'byebug'
  gem 'guard' # NOTE: this is necessary in newer versions
  gem 'guard-minitest', require: false
  gem 'guard-bundler', require: false
  gem 'guard-shell', require: false
end
```

Then run specs with `bundle exec ruby -r minitest/autorun screens.rb`.

I'm reporting this in tmate for now, because I first saw this while using tmate as a new user, but I have no idea if the culprit is in `notiffany`, in tmate itself or not etc.

**Comment by nviennot** [comment]
Yeah, so here: https://github.com/guard/notiffany/blob/master/lib/notiffany/notifier/tmux.rb#L35
You see, it expects a "X.Y" version, but tmate has version of the form "X.Y.Z" and it blows up. I'm sure this is fixable on notiffany end.

**Comment by thbar** [comment]
I see something different upon investigation: notiffany considers that we are running a tmux session if the `TMUX` environment variable is set ([relevant code](https://github.com/guard/notiffany/blob/master/lib/notiffany/notifier/tmux.rb#L13)). When tmate is running, this is apparently the case. Then right after, notiffany tries to call the (hardcoded) `tmux -V` command line ([relevant code](https://github.com/guard/notiffany/blob/master/lib/notiffany/notifier/tmux.rb#L31)).

During a tmate session, the `tmux` command is not available, which gives an empty output then the error I reported.

So I guess one possibility would be for notiffany to figure out a way to detect that `tmate` is running, rather than `tmux`.

@nviennot to your knowledge, is there something that notiffany could rely on (env var?) to reliably detect that a tmate session is going on, and not a "regular" tmux session?

**Comment by nviennot** [comment]
I'll come back to you on that

**Comment by thbar** [comment]
No hurry really - and let me know if I can help (repro, etc)!
Le ven. 25 mars 2016 à 18:19, Nicolas Viennot <notifications@github.com> a
écrit :

**Comment by nviennot** [comment]
I've updated tmate to 2.2.1. Try to see if it works better now
